In [1]:
import sys
sys.path.append("/working-files/annotations")
import torch
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
import os
from torch.utils.data.sampler import SubsetRandomSampler
import sklearn
from sklearn.metrics import confusion_matrix
from io import BytesIO
import captum
from captum.attr import IntegratedGradients
from captum.attr import visualization as viz
from captum.attr import NoiseTunnel
#from torchsummary import summary
import wget
import sqlite3, json, io
from tqdm import tqdm
import os
import numpy as np
import re
import string
from pprint import pprint
import json
import math
from math import sqrt
import torch
import itertools 
import torchtext
from torchtext.data import Field, Dataset, Example
import sklearn
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from torchtext.data import Iterator, BucketIterator
import torch.nn as nn
from torch.nn import Module
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
import tqdm
import random
import pandas as pd
from collections import Counter
from google.cloud import vision
import sys,os,json
from dotenv import load_dotenv
load_dotenv()
import pymongo
from pymongo import MongoClient
from google.cloud import vision
from google.protobuf.json_format import MessageToJson
import requests
import logging
import googletrans
from googletrans import Translator
from torch.utils.data import DataLoader
import cv2
from PIL import Image
import io
from io import BytesIO
from itertools import chain
from sklearn.metrics import confusion_matrix

In [2]:
def set_seed(seed):
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)

set_seed(1)

## Load data

In [3]:
def construct_df(annotation_json):
    data = pd.read_json(annotation_json)
    if "annotation" not in data.columns:
        df = pd.DataFrame(data.T["metadata"].tolist()).merge(pd.DataFrame(data.T["annotation"].tolist()))
    else:
        df = pd.DataFrame(data["metadata"].tolist()).merge(pd.DataFrame(data["annotation"].tolist()))
        
    return df

In [4]:
ind1 = construct_df(os.environ.get("ANNOTATION_IND1"))
ind2 = construct_df(os.environ.get("ANNOTATION_IND2")
ind3 = construct_df(os.environ.get("ANNOTATION_IND3")
ind4 = construct_df(os.environ.get("ANNOTATION_IND4")
common1 = construct_df(os.environ.get("ANNOTATION_COMMON1")
common2 = construct_df(os.environ.get("ANNOTATION_COMMON2")

In [5]:
df = common1.append(common2).append(ind1).append(ind2).append(ind3).append(ind4)

In [6]:
df.columns

Index(['_id', 'media_type', 'post_permalink', 'tag_name', 's3_url',
       'timestamp', 'caption', 'text', 'field-one', 'field-two', 'field-three',
       'field-four', 'field-five', 'field-six', 'field-seven',
       'annotator_notes', 'has_text'],
      dtype='object')

In [7]:
df.rename(columns={"field-one":"verifiable_claim", "field-two":"unidentified_video", "field-three":"contains_images",
                  "field-four":"visible_source", "field-five":"meme", "field-six":"solicitations", "field-seven":"worth_archiving"}, inplace=True)

In [8]:
df.reset_index(drop=True, inplace=True)

In [102]:
#df.to_csv("sharechat_annotated_9092020.csv")

In [9]:
images_df=df[df["media_type"]=="image"]
print(len(images_df))

1363


## Download images

In [10]:
os.chdir("working-files/annotated-images")

In [11]:
images_df.columns

Index(['_id', 'media_type', 'post_permalink', 'tag_name', 's3_url',
       'timestamp', 'caption', 'text', 'verifiable_claim',
       'unidentified_video', 'contains_images', 'visible_source', 'meme',
       'solicitations', 'worth_archiving', 'annotator_notes', 'has_text'],
      dtype='object')

In [12]:
# %%time
# for i in images_df["s3_url"]:
#     wget.download(i)

In [13]:
def claims(data):
    if "Yes" in str(data):
        return 1
    else:
        return 0

In [ ]:
images_df["claim"] = images_df["verifiable_claim"].map(claims)

In [15]:
images_df[["verifiable_claim","claim"]][:5]

verifiable_claim  claim
0  [Yes, Descriptions of a real world events/plac...      1
3                                              [No ]      0
4                                              [No ]      0
7  [Yes, Descriptions of a real world events/plac...      1
8  [Yes, Descriptions of a real world events/plac...      1

## Download word embeddings and extract text from images

In [16]:
# wget.download("https://dl.fbaipublicfiles.com/fasttext/vectors-aligned/wiki.hi.align.vec")

In [17]:
def get_image_text(path, client):  
    def detect_text(img_bytes, client):
        image_data = vision.types.Image(content=img_bytes)
        resp = client.text_detection(image=image_data)
        resp = json.loads(MessageToJson(resp))
        text = resp.get('fullTextAnnotation',{}).get("text","")
        return text
    image = Image.open(path, mode="r")
    imgByteArr = io.BytesIO()
    image.save(imgByteArr, format="PNG")
    img_bytes = imgByteArr.getvalue()
    text = detect_text(img_bytes, client)
    return text

In [18]:
# %%time
# f=0
# extractions = {}
# texts = []
# client = vision.ImageAnnotatorClient()
# img_folder = os.getcwd()
# for i in os.listdir(img_folder):
#     try:
#         text = get_image_text(i, client)
#         extractions[i] = text
#         texts.append(text)
#     except:
#         f+=1
#         extractions[i] = ""
#         texts.append("")

In [157]:
# with open("extractions.json","w") as f:
#     json.dump(extractions, f)

In [19]:
with open("../extractions.json","r") as f:
    extractions = json.loads(f.read())

In [20]:
def match_texts(url):
    filename = url.split("/")[-1]
    text = extractions.get(filename)
    return text

In [21]:
def get_filename(url):
    return url.split("/")[-1]

In [ ]:
images_df["extracted_text"] = images_df["s3_url"].map(match_texts)

In [23]:
images_df.tail(5)["post_permalink"]

2191     https://sharechat.com/post/pAvG5KK
2192     https://sharechat.com/post/8Vvgx0V
2193     https://sharechat.com/post/8nd1zAw
2194     https://sharechat.com/post/xn9e3vw
2197    https://sharechat.com/post/8rZ4Zbzj
Name: post_permalink, dtype: object

In [24]:
images_df.tail(5)["extracted_text"]

2191    मृत्यु भोज समाज के लिये अभिशाप : जगतगुरु\nने स...
2192    share plz\nall group\nअगर किसी की दोनो किउनिया...
2193                                      HindiSoch.Com\n
2194    LIFES 6 RULES FOR SUCCESS:\nI. TRUST YOURSELF\...
2197    All Problem Solution Specialist Astrologer\n+9...
Name: extracted_text, dtype: object

In [25]:
images_df["claim"].value_counts()

0    802
1    561
Name: claim, dtype: int64

In [ ]:
images_df["filename"] = images_df["s3_url"].map(get_filename)

In [27]:
claims_df = images_df[["filename", "extracted_text", "claim"]].reset_index(drop=True)

In [28]:
claims_df.rename(columns={"filename":"img_name", "extracted_text":"text","claim":"label"}, inplace=True)

## Load images, labels and image text 

In [30]:
transformations=transforms.Compose([
                    transforms.Resize((224,224)), 
                    transforms.ToTensor(),
                    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])

class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, img_dir, texts_and_labels, transform):
        if isinstance(texts_and_labels, pd.core.frame.DataFrame):
            df = texts_and_labels
        else:
            # initial model training data was loaded this way
            with open(texts_and_labels, "r") as fp:
                data = json.load(fp)
            df = pd.DataFrame.from_dict(data, orient="index").reset_index()
            df.columns = ["img_name", "text"]
            df["label"] = df["img_name"].apply(lambda x: 0 if "neg" in x else 1)
        self.img_dir=img_dir
        self.img_names=df["img_name"].values
        self.text = df["text"].values
        self.y = df["label"].values
        self.transform=transform
        
    def __getitem__(self, idx):
        # For each img_name in img_names, load the corresponding img from the img folder
        img = Image.open(os.path.join(self.img_dir, self.img_names[idx])).convert('RGB')
        # Return the transformed RGB image
        if self.transform is not None:
            img_vector=self.transform(img)
        
        # Return the corresponding label and text
        label = self.y[idx]
        text = self.text[idx]
        return img_vector,label,text
    
    def __len__(self):
        return self.y.shape[0]
    

In [31]:
dataset = CustomDataset(
                       img_dir=os.environ.get("IMAGE_FOLDER"),
                       texts_and_labels=claims_df,
                       transform=transformations)

## Create text preprocessing pipeline

In [69]:
def load_embeddings(path):
    """ Loads pretrained aligned word embeddings """
    print("Loading pretrained aligned word embeddings")
    words = []
    idx = 0
    word2idx = {}
    vectors = []
    fin = io.open(path, 'r', encoding='utf-8', newline='\n', errors='ignore')
    n, d = map(int, fin.readline().split())
    for line in tqdm.tqdm(fin,total=n):
        tokens = line.rstrip().split(' ')
        vec = (list(map(float, tokens[1:])))
        word = tokens[0].replace("'",'"')
        words.append(word)
        word2idx[word]=idx
        vectors.append(vec)
        idx+=1
    print("Number of embeddings loaded: ", len(vectors))
    vectors = np.array(vectors)
    aligned_dict = {w: vectors[word2idx[w]] for w in words}
    return aligned_dict

def prepare_sequences(dataloader, inference=False, pretrained=None, vocab2index=None):
    """ Encodes text into sequences of vocabulary indices """
    
    def tokenize(text):
        """ Removes punctuation and numbers, converts to lowercase and splits into individual words """
        regex = re.compile('[' + re.escape(string.punctuation) + '0-9\\r\\t\\n\।]') # last character । is the Hindi full stop
        nopunct = regex.sub(" ", text.lower())
        tokenized_text = [token for token in nopunct.split(" ") if len(token) > 0]
        return tokenized_text
    
    def count_words(tokens, counts):
        """ Counts unique words in text """
        counts.update(list(chain.from_iterable(tokens)))
        return counts
    
    def get_emb_matrix(pretrained, word_counts, emb_size = 300):
        """ Creates training vocabulary, vocab2index and embedding matrix from pretrained word vectors """
        found=0
        not_found=0
        vocab_size = len(word_counts) + 2
        vocab_to_idx = {}
        vocab = ["", "UNK"]
        W = np.zeros((vocab_size, emb_size), dtype="float32")
        W[0] = np.zeros(emb_size, dtype='float32') # adding a vector for padding
        W[1] = np.random.uniform(-0.25, 0.25, emb_size) # adding a vector for unknown words 
        vocab_to_idx["UNK"] = 1
        i = 2
        for word in word_counts:
            if word in pretrained:
                W[i] = pretrained[word]
                found+=1
            else:
                W[i] = np.random.uniform(-0.25,0.25, emb_size)
                not_found+=1
            vocab_to_idx[word] = i
            vocab.append(word)
            i += 1   
        return W, np.array(vocab), vocab_to_idx, found, not_found
    
    def encode_tokens(tokenized_text, vocab2index, N=50): # keep max doc length to 50 words
        """ Encodes tokenized text into equal length sequences of vocabulary indices """ 
        sequences = []
        for text in tokenized_text:
            seq = np.zeros(N, dtype=int)
            # get word index if it's in vocab else get default index
            enc = np.array([vocab2index.get(word, vocab2index["UNK"]) for word in text])
            # limit sequence length
            length = min(N, len(enc))
            seq[:length] = enc[:length]
            sequences.append(seq)
        return sequences

    if inference==False:
        counts = Counter()
        tokenized_text = []
        print("Tokenizing text and counting unique words")
        for i in dataloader:
            tokenized = [tokenize(doc) for doc in i[2]]
            counts = count_words(tokenized, counts)
            tokenized_text.extend(tokenized)  

        print("Creating vocab2index and embedding matrix with pretrained weights")
        pretrained_weights, vocab, vocab2index, found, not_found = get_emb_matrix(pretrained, counts)
        sequences = encode_tokens(tokenized_text, vocab2index)
        vocab_size = len(vocab)
        print("Finished preparing sequences")
        return sequences, vocab, vocab_size, vocab2index, pretrained_weights
    else:
        print("Tokenizing text")
        tokenized_text = []
        for i in dataloader:
            tokenized = [tokenize(doc) for doc in i[2]]
            tokenized_text.extend(tokenized)
        sequences = encode_tokens(tokenized_text, vocab2index)
        print("Finished preparing sequences")
        return sequences

## Train-validation split

In [70]:
# Shuffle and randomly split dataset into 80:20 training and validation sets
train_size = int(0.8 * len(dataset))
valid_size = len(dataset) - train_size
train_dataset, valid_dataset = torch.utils.data.random_split(dataset, [train_size, valid_size])

In [71]:
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=8, shuffle=False)
validation_loader = torch.utils.data.DataLoader(valid_dataset, batch_size=8, shuffle=False)

In [ ]:
path = os.environ.get("EMBEDDINGS_PATH")
aligned_dict = load_embeddings(path)

In [74]:
train_sequences, vocab, vocab_size, vocab2index, pretrained_weights = prepare_sequences(train_loader, inference=False, pretrained=aligned_dict)

  0%|          | 786/158016 [00:00<00:20, 7856.79it/s]

Loading pretrained aligned word embeddings


100%|██████████| 158016/158016 [00:16<00:00, 9783.35it/s] 


Number of embeddings loaded:  158016
Tokenizing text and counting unique words
Creating vocab2index and embedding matrix with pretrained weights
Finished preparing sequences


In [75]:
valid_sequences = prepare_sequences(validation_loader, inference=True, vocab2index=vocab2index)

Tokenizing text
Finished preparing sequences


In [76]:
train_seq_loader = torch.utils.data.DataLoader(train_sequences, batch_size=8, shuffle=False)
valid_seq_loader = torch.utils.data.DataLoader(valid_sequences, batch_size=8, shuffle=False)

In [77]:
# for k, v in vocab2index.items():
#     if v==102:
#         print (k)

# vocab2index["कर"]

## Build model

In [78]:
class FusionModel(torch.nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, pretrained_weights, num_labels):
        super().__init__()
        # LSTM layers
        self.embeddings = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.embeddings.weight.data.copy_(torch.from_numpy(pretrained_weights))
        self.embeddings.weight.requires_grad = False ## freeze embeddings
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.linear = nn.Linear(hidden_dim, 100)
        #self.dropout = nn.Dropout(0.2)
        # ResNet layers
        self.resnet = models.resnet18(pretrained=True)
        for param in self.resnet.parameters():
            param.requires_grad = False
        # Replace the default ResNet18 classifier layer 
        classifier_input = self.resnet.fc.in_features
        classifier = nn.Sequential(nn.Linear(classifier_input, 100), 
                             nn.LogSoftmax(dim=1)) 
        self.resnet.fc = classifier
        self.fusion_classifier = nn.Linear(200,2)
        
    def forward(self, x1, x2): # image vector, encoded image text
#         print("x1:",x1)
#         print("x2",x2)
        # Image
        x1_out = self.resnet(x1)
        # Text
        x2_embed = self.embeddings(x2)
        #x2_dropout = self.dropout(x2_embed)
#         print("img representation:",x1_out)
#         print("")
        lstm_out, (ht, ct) = self.lstm(x2_embed)
        x2_out = self.linear(ht[-1])
#         print("text representation:",x2_out)
#         print("")
        # Concatenation
        fused = torch.cat([x2_out, x1_out], dim=1)
#         print("fused:", fused)

        return self.fusion_classifier(fused)

In [79]:
model = FusionModel(vocab_size=vocab_size, embedding_dim=300, hidden_dim=5, pretrained_weights=pretrained_weights,
                    num_labels=2)

## Train model

In [80]:
def train_model(model, epochs, lr, train_loader, train_seq_loader):
    parameters = filter(lambda p: p.requires_grad, model.parameters())
    optimizer = torch.optim.Adam(parameters, lr=lr)
    model.train()
    for i in range(epochs):
        sum_loss = 0.0
        total = 0
        correct = 0
        for i, data in enumerate(zip(train_loader, train_seq_loader)):
        #for data in zip(validation_loader, valid_seq_loader): 
            img_vectors, text_sequences, y_train = data[0][0], data[1], data[0][1]      
            optimizer.zero_grad()
            y_hat = model(img_vectors, text_sequences)
            loss = F.cross_entropy(y_hat, y_train)
            loss.backward()
            optimizer.step()
            sum_loss += loss.item()*y_train.shape[0]
            total += y_train.shape[0]
            pred = torch.max(y_hat, 1)[1]
            correct += (pred == y_train).float().sum()
        val_loss, val_acc = validation_metrics(model, validation_loader, valid_seq_loader)
        print("train loss %.3f, train accuracy %.3f, val loss %.3f, val accuracy %.3f" % (sum_loss/total, correct/total, val_loss, val_acc))

def validation_metrics (model, validation_loader=validation_loader, valid_seq_loader=valid_seq_loader):
    # Initialize the prediction and label lists(tensors)
    predlist=torch.zeros(0,dtype=torch.long, device='cpu')
    lbllist=torch.zeros(0,dtype=torch.long, device='cpu')
    model.eval()
    correct = 0
    total = 0
    sum_loss = 0.0
    for i, data in enumerate(zip(validation_loader, valid_seq_loader)):
        #
        img_vectors, text_sequences, y_valid = data[0][0], data[1], data[0][1] 
        y_hat = model(img_vectors, text_sequences)
        loss = F.cross_entropy(y_hat, y_valid)
        #print("y_hat:",y_hat)
        pred = torch.max(y_hat, 1)[1]
        #print("pred:",pred)
        # Append batch prediction results
        predlist=torch.cat([predlist,pred.view(-1).cpu()])
        lbllist=torch.cat([lbllist,y_valid.view(-1).cpu()])
        # Calculate accuracy
        correct += (pred == y_valid).float().sum()
        total += y_valid.shape[0]
        sum_loss += loss.item()*y_valid.shape[0]
    
    # Confusion matrix
    conf_mat=confusion_matrix(lbllist.numpy(), predlist.numpy())
    print(conf_mat)
    
    # Per-class accuracy
    class_accuracy=100*conf_mat.diagonal()/conf_mat.sum(1)
    print(class_accuracy)
    
    return sum_loss/total, correct/total

In [82]:
%%time
train_model(model=model, epochs=10, lr=0.001, train_loader=train_loader, train_seq_loader=train_seq_loader)

[[ 74  86]
 [  9 104]]
[46.25       92.03539823]
train loss 0.561, train accuracy 0.732, val loss 0.658, val accuracy 0.652
[[ 96  64]
 [ 12 101]]
[60.         89.38053097]
train loss 0.451, train accuracy 0.794, val loss 0.574, val accuracy 0.722
[[101  59]
 [ 13 100]]
[63.125      88.49557522]
train loss 0.412, train accuracy 0.812, val loss 0.554, val accuracy 0.736
[[ 99  61]
 [ 11 102]]
[61.875      90.26548673]
train loss 0.382, train accuracy 0.829, val loss 0.561, val accuracy 0.736
[[ 90  70]
 [ 11 102]]
[56.25       90.26548673]
train loss 0.359, train accuracy 0.841, val loss 0.605, val accuracy 0.703
[[117  43]
 [ 18  95]]
[73.125      84.07079646]
train loss 0.324, train accuracy 0.848, val loss 0.526, val accuracy 0.777
[[ 97  63]
 [ 12 101]]
[60.625      89.38053097]
train loss 0.301, train accuracy 0.875, val loss 0.609, val accuracy 0.725
[[116  44]
 [ 17  96]]
[72.5        84.95575221]
train loss 0.275, train accuracy 0.880, val loss 0.537, val accuracy 0.777
[[111  4